### PR TITLE
Add model-space ensemble spread to diagnostics

### LINKED ISSUE #94: Add model-space ensemble spread diagnostics
Corresponds to https://github.com/JCSDA-internal/mpas-jedi/issues/711

Progress here: https://github.com/NCAR/MPAS-Workflow/tree/feature/modelEnsembleDiags

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description

Utilizes new diagnostic functionalities in mpas-jedi for model-space ensemble spread.  Includes modifications to the RTPP task in order to allow the analysis ensemble spread to be diagnosed before the relaxation is applied.

Adds `retain*` options in the `variational`, `hofx`, and `rtpp` applications to allow users to decide whether to retain re-creatable data files and incur the extra disk space requirement.  The default for `variational.retainObsFeedback` and `hofx.retainObsFeedback` is True, then set to False for all EDA scenarios.  The default for `rtpp.retainOriginalAnalyses` is False.

### Issue closed

Closes #94 

### Related PR's

- https://github.com/JCSDA-internal/mpas-jedi/pull/712

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

### CODE REVIEW

**Comment by ibanos90** [comment]
Hi @jjguerrette. The addition of the  `retain*` options is very interesting. I wonder if then we can remove the `GOMsaver` filter from the yamls?
e.g,
https://github.com/NCAR/MPAS-Workflow/blob/937cab79e1cf439eff2a2f48a66dfa3eae59220d/config/ObsPlugs/hofx/filters/amsua_aqua.yaml#L4-L5

**Comment by ibanos90** [comment]
> Hi @jjguerrette. The addition of the `retain*` options is very interesting. I wonder if then we can remove the `GOMsaver` filter from the yamls? e.g,
> 
> https://github.com/NCAR/MPAS-Workflow/blob/937cab79e1cf439eff2a2f48a66dfa3eae59220d/config/ObsPlugs/hofx/filters/amsua_aqua.yaml#L4-L5

Sorry, I got confused. We still need the `GOMsaver` filter in the yamls because it actually allows the writing of the files, right?

**Comment by jjguerrette** [comment]
> Sorry, I got confused. We still need the `GOMsaver` filter in the yamls because it actually allows the writing of the files, right?

Yes, we still need the `GOMsaver` for some diagnostic binning.

**Comment by ibanos90** [comment]
> > Sorry, I got confused. We still need the `GOMsaver` filter in the yamls because it actually allows the writing of the files, right?
> 
> Yes, we still need the `GOMsaver` for some diagnostic binning.

Thanks @jjguerrette.

**Review by ibanos90 — APPROVED** [review]
Ran the tests and all completed successfully.

**Pull request merged**
