### PR TITLE
Make init and execute TaskFamily members yaml-configurable

### LINKED ISSUE #143: Independent control of extended forecasts and obs-space/model-space verification statistics
Currently the forecast step and verification step runs together, better we can control independently to run the forecast step and verification statistics step.

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
Enables application-independent control of family sub-tasks via the `initialize` and `execute` options.  An example is added in `test/testinput/3dvar_OIE120km_WarmStart_PostProcess.yaml`.  For brevity, here is an excerpt:
```yaml
extendedforecast:
  meanTimes: T00
  lengthHR: 24
  outIntervalHR: 12
  execute: True # or False
  post: [verifyobs, verifymodel]  # [] to disable
forecast:
  execute: False # or True
  post: [verifyobs, verifymodel]  # [] to disable
variational:
  DAType: 3dvar
  nInnerIterations: [15,]
  execute: False # or True
  post: [verifyobs] # [] to disable
```

Each of `extendedforecast`, `forecast`, and `variational` demonstrate their independent `execute` and `post` options.  Users can also turn on/off the init task (only applies to DA) with the `initialize` yaml key; however, `initialize` is automatically disabled unless `execute` is `True`.  This new functionality entirely supersedes that formerly accomplished with `CriticalPathType`.  Therefore, `CriticalPathType` is deprecated.

Output generated with `cylc gscan` when only extended forecast verification is turned on in a `Cycle` suite:
Screen Shot 2023-04-04 at 1 24 20 PM

A new `test2.yaml` is added that can be run manually after `test1.yaml` completes to ensure the independent post-processing works as expected. However, I could not figure out a way to submit a suite automatically after an earlier suite completed.

### Issue closed

Closes #143

#### Tier 1:
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_IAU_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3dvar_O30kmIE60km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart
 - [x] getkf_OIE120km_WarmStart

### CODE REVIEW

**Comment by syha** [comment]
Looks good to me, but what does 'meanTimes' mean? It's not so intuitive...

**Comment by jjguerrette** [comment]
> Looks good to me, but what does 'meanTimes' mean? It's not so intuitive...

Well if you look at initialize/applications/ExtendedForecast.py, there are two options: `meanTimes` and `ensTimes`

Names of those options can change, but the functionality is to either initialize forecasts at mean analyses or ensemble member forecasts.  Any suggestions for names?

**Comment by jjguerrette** [comment]
Note that this documentation of options within the derived Component python classes is common across the repo, except for HPC-specific settings that are described in scenarios/defaults/*.yaml.

**Comment by syha** [comment]
I see. So the mean vs. ens, it was. I didn't think of the case with different Times for mean and ens, but if that's how it works here, then ok. Thanks for the reply!

**Comment by jjguerrette** [comment]
@syha and @byoung-joo: the latest commit _should_ fix the issue you both encountered with getting kicked off the login node during extended forecast verification

**Comment by jjguerrette** [comment]
Standard tests are in progress.  A new `test2.yaml` is added that can be run after `test1.yaml` to ensure the independent post-processing works as expected.  However, I could not figure out a way to submit a suite automatically after an earlier suite completed.

**Comment by jjguerrette** [comment]
All tests pass.  Note that this feature branch is based off of feature/letkf.  #207 needs to be merged before this PR.

**Comment by jjguerrette** [comment]
> > Looks good to me, but what does 'meanTimes' mean? It's not so intuitive...
> 
> Well if you look at initialize/applications/ExtendedForecast.py, there are two options: `meanTimes` and `ensTimes`
> 
> Names of those options can change, but the functionality is to either initialize forecasts at mean analyses or ensemble member forecasts. Any suggestions for names?

@syha, what about `mean ic times` and `ensemble ic times`?

**Review by liujake — APPROVED** [review]
You may merge whenever you are ready.

**Comment by syha** [comment]
Yes, that sounds better.

**Review by syha — APPROVED** [review]

**Pull request merged**
