### PR TITLE
Updates for IODA v3

### LINKED ISSUE #175: Make changes needed for observation convention updates
See https://github.com/orgs/JCSDA-internal/teams/jedi-models/discussions/91

Due 17JAN2022 (earlier better)

- [x] Update all pre-generated observation files (@junmeiban)
  - [x] sondes
  - [x] satwind
  - [x] sfc
  - [x] gnssro
  - [x] aircraft
  - [x] amsua
  - [x] mhs
  - [x] ahi
  - [x] abi
  - [x] iasi
- [x] Update YAMLS (@jjguerrette)
- [ ] New build (@jjguerrette)
- [x] Update https://github.com/NCAR/MPAS-Workflow/blob/develop/ObsToIODA.csh (not time sensitive since nobody is running real-time right now)

Working branch: https://github.com/NCAR/MPAS-Workflow/tree/feature/sprint-ioda-converters

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description

- YAML stubs are updated with new variable names
- `ObsToIODA.csh` now converts all observation files to the v3 conventions
- The pre-generated observation files used for the 2018 period are all updated (contributed by @junmeiban)

### Issue closed

Closes #175 

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3dvar_O30kmIE60km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

### CODE REVIEW

**Comment by jjguerrette** [comment]
I am presently running `test.csh`.  Will check boxes as tests finish.

@junmeiban, one remaining item is to copy/move the new observation files from `/glade/scratch/jban/pandac/obsiodav3_221216/newobs_2018` to somewhere on `/glade/p/mmm/parc`.  Then `observations` yaml sections in this PR need to be updated with the new directory.

**Comment by liujake** [comment]
@jjguerrette @junmeiban I am copying /glade/scratch/jban/pandac/obsiodav3_221216 to /glade/p/mmm/parc/liuz/pandac_common/.

**Comment by jjguerrette** [comment]
All tests completed successfully.

**Review by junmeiban — APPROVED** [review]
Also tested on Cheyenne and ran successfully.

**Pull request merged**
