### PR TITLE
Enable flexibility for non-bundle Forecast build

### LINKED ISSUE #216: Enable non-bundle mpas atmosphere executable
Requested by @liujake

Feature branch: https://github.com/NCAR/MPAS-Workflow/tree/feature/nonBundleForecast

Base branch: feature/optionalInitANDExecution

Diff: https://github.com/NCAR/MPAS-Workflow/compare/feature/optionalInitANDExecution...feature/nonBundleForecast

A scenario YAML option named `build.forecast directory` is added that allows users to simply set the directory where the `init_atmosphere_model` and `atmosphere_model` executables are located.  The default is `bundle`, which uses the `mpas bundle` directory and JEDI environment.

The environment for the non-bundle executable is defined in `config/environmentForecast.csh`, including the mpi command (e.g., mpiexec_mpt) that should be used.

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
A scenario YAML option named `build.forecast directory` is added that allows users to simply set the directory where the `init_atmosphere_model` and `atmosphere_model` executables are located.  The default is `bundle`, which uses the `mpas bundle` directory and JEDI environment.

The environment for the non-bundle executable is defined in `config/environmentForecast.csh`, including the mpi command (e.g., mpiexec_mpt) that should be used.

### Issue closed

Closes #216 

#### Tier 1:
 - [x] 3dvar_OIE120km_WarmStart
 - [x] ForecastFromGFSAnalysesMPT
 
As long as a bundle forecast and a non-bundle forecast executable are successful, then this PR is correct.  No need to run other Tier 1 tests.

### CODE REVIEW

**Comment by jjguerrette** [comment]
@liujake, can you either try this or share a glade directory where your intel-mpt build is located?

Also, please include a list of environment modules you are loading for building/running.

**Comment by liujake** [comment]
Recently I used is /glade/p/mmm/parc/liuz/pandac_hybrid/20221205_mpas_bundle_SP/MPAS_intelmpt/. It was built with loaded modules below:
```
source /etc/profile.d/modules.csh
module purge
module load intel/19.0.5
module load mpt/2.22
module load netcdf-mpi/4.7.3
module load pnetcdf/1.12.1
module load pio/2.4.4
module load ncarenv/1.3
module load ncview/2.1.7
module load graphviz/2.40.1
module load ncarcompilers/0.5.0
module load nco/4.7.9
module load python/3.7.5
module load ncl/6.6.2

limit stacksize unlimited
```

**Comment by jjguerrette** [comment]
Thanks.  I'm adding a test case, and will push changes here when ready.

**Comment by jjguerrette** [comment]
I can't get the MPT build to work yet, because the build uses a different version of MPAS-Model.  The version used in the workflow by default includes 50hPa and 100hPa forecast diagnostics.  Those are not available in `/glade/p/mmm/parc/liuz/pandac_hybrid/20221205_mpas_bundle_SP/MPAS_intelmpt/`.

See https://github.com/JCSDA-internal/MPAS-Model/pull/42

**Comment by liujake** [comment]
I will make another build based on the latest version of model code.

**Comment by liujake** [comment]
new build: /glade/p/mmm/parc/liuz/pandac_common/20230406_mpas_bundle/MPAS_intelmpt

**Review by liujake — APPROVED** [review]
Looks good! Note that my current intel+mpt built code has the scale-aware new Tiedtke modifications, not ready yet to be used in cycling experiments. Plan to commit the 'official' scale-aware code from Wei Wang to the model repo. at some point for the group's use. This code should also be included in MPAS-v8.0 release.

**Pull request merged**
