### PR TITLE
Fixed a few 30km scenarios with proper node/core setting on derecho

### PR DESCRIPTION
**Pull request by liujake**
### Description
These 30km-60km dual-res. hybrid-3DEnVar and 4DEnVar scenarios are still using the old node/core
setting on cheyenne. This PR changed the settings to be appropriate on derecho. Also deleted one
obsolete scenario with no VarBC.

### List of modified files
	deleted:    scenarios/3dhybrid_O30kmIE60km_SpecifiedEnsemble.yaml
	modified:   scenarios/3dhybrid_O30kmIE60km_SpecifiedEnsemble_VarBC.yaml
	modified:   scenarios/3dhybrid_O30kmIE60km_SpecifiedEnsemble_VarBC_iasi.yaml
	modified:   scenarios/4denvar_O30kmIE60km_WarmStart_VarBC_7slots_2outer_80mem.yaml
	modified:   scenarios/defaults/variational.yaml

### CODE REVIEW

**Comment by liujake** [comment]
I have not checked all cycling scenarios for proper node/core settings. These are what I checked/tested so far.

**Comment by liujake** [comment]
For a record here: the scenario with IASI failed for the second cycle, seemingly without an error message. Might be caused by insufficient memory using 2 nodes. The first cycle was successful for me. @zhumingying how many nodes/cores you used for your IASI/CrIS experiments?

**Comment by jim-p-w** [comment]
When I saw some tasks were failing due to out of memory, the email for the task contained `Exit_status=265
`

**Comment by liujake** [comment]
@jim-p-w I deleted email notifications. 
One another note: I also tested 3dhybrid_OIE120km_WarmStart.yaml, but failed if I remember correctly.

**Review by RGNystrom — APPROVED** [review]

**Pull request merged**
