### PR TITLE
Update data path. Continued.

### PR DESCRIPTION
**Pull request by junmeiban**
### Description
This PR is about changes of data path (continued, after https://github.com/NCAR/MPAS-Workflow/pull/229):
1. The path for static B, ensemble localization, mpas_bundle(single precision), and mpas_model (outside bundle, intel+mpt) are updated.
2. All obs locations are updated in scenarios/*yaml and test/testinput/*yaml  (**only tested 3dhybrid scenarios**)
3. Modified "config/jedi/applications/3dhybrid.yaml" according to https://github.com/JCSDA-internal/mpas-jedi/pull/868

### Files modified:
M       config/jedi/applications/3dhybrid.yaml
M       initialize/framework/Build.py
M       scenarios/defaults/variational.yaml
M       scenarios/3denvar_O30kmIE60km_WarmStart.yaml
M       scenarios/3denvar_O30kmIE60km_WarmStart_ABEI.yaml
M       scenarios/3denvar_O30kmIE60km_WarmStart_SpecifiedEnsemble.yaml
M       scenarios/3dhybrid_O30kmIE60km_SpecifiedEnsemble.yaml
M       scenarios/IASI30kmIE60km3denvar.yaml
M       scenarios/eda_OIE60km_WarmStart.yaml
M       scenarios/getkf_OIE60km_WarmStart.yaml
M       scenarios/letkf2D_OIE60km_WarmStart.yaml
M       scenarios/letkf_OIE60km_WarmStart.yaml
M       test/testinput/3denvar_O30kmIE60km_WarmStart.yaml

P.S.:
Some of the fixed input are still sitting outside Jake's "pandac_common". The issue https://github.com/NCAR/MPAS-Workflow/issues/225 cannot be closed so far. 

#### Tier 1:
 - [x] 3dhybrid_O30kmIE60km_SpecifiedEnsemble_VarBC.yaml

### CODE REVIEW

**Comment by junmeiban** [comment]
@byoung-joo , when you are available, would you please make sure the change I made in config/jedi/applications/3dhybrid.yaml? Many thanks. No hurry.

**Comment by junmeiban** [comment]
My working path: /glade/scratch/jban/pandac/jban_3dhybrid-60-60-iter_O30kmI60km_ensB-SE80+RTPP70_VarBC/

**Comment by liujake** [comment]
@byoung-joo Do we need to re-generate 120km bump localization files with the latest new code for 3DEnVar? @ibanos90 had trouble to run 120km 3DEnVar with old (22 March) localization files. You may generate new 120km localization files, which can be included in this or next PR.

**Comment by byoung-joo** [comment]
> @byoung-joo Do we need to re-generate 120km bump localization files with the latest new code for 3DEnVar?

I didn't generate the 120 km one. I will regenerate it soon.

**Comment by liujake** [comment]
During my absence, you may put your input files under your own disk space and point to your locations in Workflow. I will copy over after I am back and then we can update Workflow. It would be good to have a working workflow with new code/files for both 120km and 30km-60km during the next week so that your three can work with the same version of Workflow for different things.

**Review by liujake — APPROVED** [review]
Looks good to me.

**Comment by byoung-joo** [comment]
> During my absence, you may put your input files under your own disk space and point to your locations in Workflow. I will copy over after I am back and then we can update Workflow. It would be good to have a working workflow with new code/files for both 120km and 30km-60km during the next week so that your three can work with the same version of Workflow for different things.


@liujake, That makes sense. 

- I will regenerate the 120 km bump localization files and put my path in the workflow. 
- I also need to update the link for the 120 km static B files in the workflow.

For now all 120 km scenarios will fail w/ develop branch.

 
> @byoung-joo , when you are available, would you please make sure the change I made in config/jedi/applications/3dhybrid.yaml? Many thanks. No hurry.

@junmeiban,
we also need to update the `3dvar.yaml`, `3denvar.yaml`, and `3denvar-crossed.yaml` similar to `3dhybrid.yaml`: `bump` --> `read`, but this can be done in next PR.

**Comment by junmeiban** [comment]
> @junmeiban, we also need to update the `3dvar.yaml`, `3denvar.yaml`, and `3denvar-crossed.yaml` similar to `3dhybrid.yaml`: `bump` --> `read`, but this can be done in next PR.

Many thanks @byoung-joo . I updated the three yamls.

**Comment by byoung-joo** [comment]
@junmeiban, can you modify 120km B-related path in `scenarios/defaults/variational.yaml` as below ?  Or I can push a commit and run some test!

- `localization.120km.bumpLocDir` --> `/glade/scratch/bjung/pandac/20230522_yr5/120km.bumploc.duplicated.limited.1200km6km`
- `covariance.120km.bumpCovDir` --> `/glade/scratch/bjung/pandac/20230522_yr5/120km.NICAS_00`
- `covariance.120km.bumpCovStdDevFile` -->`/glade/scratch/bjung/pandac/20230522_yr5/120km.CMAT_00/mpas.stddev_0p33.2018-04-15_00.00.00.nc`
- `covariance.120km.bumpCovVBalDir` -->`/glade/scratch/bjung/pandac/20230522_yr5/120km.VBAL_00`

**Comment by liujake** [comment]
@byoung-joo You may test them in your local workflow and then I can copy them over this evening once you confirm they work properly.

**Comment by liujake** [comment]
@byoung-joo @junmeiban I merged this one. @byoung-joo  may make the next PR after tested 120km files and I copy them over.

**Comment by liujake** [comment]
@byoung-joo I already copied 120km files to /glade/p/mmm/parc/liuz/pandac_common/BUMP_files/20230522_yr5.

**Comment by byoung-joo** [comment]
Thank you, @liujake .
I will test the 120 km scenarios and make a new PR for replacing the 120 km paths!

**Pull request merged**
