### PR TITLE
Enable automated testing and user-defined scenario selection

### LINKED ISSUE #68: Automated testing across experiment configurations

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description

Three new sets of functionality are enabled.  Please note that `README.md` is updated with much of this information.  Here is a more verbose design description.

#### 1. Scenario Configuration
There is a one-to-one correspondence between config files under `scenarios/base/*.yaml` and the scripts of the same name located at `config/*.csh`.  Those yaml files contain the default settings and full descriptions of all user-configurable options.  Combined with `tools/getYAMLKey.py`, `config/setConfig.csh`, and `config/getConfigOrNone.csh`, these scenario settings control the top-level configuration variables of individual experiments.  For example, an excerpt from `scenarios/base/workflow.yaml` contains default settings as follows:
```yaml
workflow:
  firstCyclePoint: 20180414T18
  initialCyclePoint: 20180414T18
  finalCyclePoint: 20180514T18
  InitializationType: WarmStart
  CriticalPathType: Normal
...
```

The base configurations are named as follows:
```
workflow.yaml - cylc task selection and date bounds
experiment.yaml - experiment naming conventions
model.yaml - model mesh settings
observations.yaml - observation source data
variational.yaml - settings specific to the variational application
hofx.yaml - settings specific to the hofx application
job.yaml - account and queue selection
```

Then there are specific scenario files (`scenarios/*.yaml` and `scenarios/testinput/*.yaml`) that show users the settings that would typically be modified away from their default values in order to run actual experiments.  The user selects a specific scenario by modifying `config/scenario.csh`.  They may choose from the following options presently:
 - 3dvar_OIE120km_WarmStart
 - 3dvar_OIE120km_ColdStart
 - 3denvar_OIE120km_WarmStart
 - 3denvar_O30kmIE60km_WarmStart
 - 3denvar_O30kmIE60km_WarmStart_ABEI
 - 3dhybrid_OIE120km_WarmStart (experimental, tested for one cycle)
 - eda_OIE120km_WarmStart
 - eda_OIE60km_WarmStart (experimental)

`3dvar_OIE120km_WarmStart` is set as the default scenario, consistent with the current behavior in the `develop` branch.

#### 2. Automated testing
A new script is added, `run.csh`, which runs the 5 test scenarios recommended for every pull request.  This is accomplished with the command, `./run.csh test` or simply `./test.csh`, executed in the repository directory.  There are additional options for the argument to `run.csh` so that a non-expert user can easily switch between the run config files under `runs/*.yaml` without needing to know what lies underneath in the whole `config` and `scenarios` directories.  This acts as a pass-through to avoid manually modifying `config/scenario.csh`.  The options for the command-line argument to `run.csh` are as follows:
```shell
set ValidRunConfigs = ( \
  test \
  120km3dvar \
  120km3denvar \
  120kmEDA \
  60kmEDA \
  30km-60km3denvar \
)
```

#### 3. config files are sourced only once
Similar to the functionality of an IFDEF statement used  in a C or C++ header file, checks are added in commonly used config files to avoid re-sourcing them multiple times.  This avoids unnecessary and time-consuming double loading of large numbers of environment variables and settings.  For example, the python environment need only be loaded once, so `config/environmentPython.csh` begins with:
```shell
if ( $?config_environmentPython ) exit 0
setenv config_environmentPython 1
```

### Issue closed

Closes #68 

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

### CODE REVIEW

**Comment by jjguerrette** [comment]
Will run tests now.

**Comment by jjguerrette** [comment]
Reverting to draft until after testing is complete.  Need to fix some bugs I think.

**Comment by jjguerrette** [comment]
Ready for review.  ~~Two tests still running.~~

**Comment by ibanos90** [comment]
These new functionalities are very nice to have! Just one thing. When executing the autotest-PR.csh script I get the following messages:
```
nEnsDAMembers: Undefined variable.
variationalObsList: Undefined variable.
nEnsDAMembers: Undefined variable.
```
Nevertheless, the 5 test cases completed successfully.

**Comment by jjguerrette** [comment]
Thank you @ibanos90!  I figured out what was going on.  Just to confirm, do you still intend to remove the VARBC table settings in SetupWorkflow.csh?  If so, I would like to remove them in this PR to avoid the headache of coming up with a workaround that will not be needed one or two PR's ahead.

**Comment by ibanos90** [comment]
> Thank you @ibanos90! I figured out what was going on. Just to confirm, do you still intend to remove the VARBC table settings in SetupWorkflow.csh? If so, I would like to remove them in this PR to avoid the headache of coming up with a workaround that will not be needed one or two PR's ahead.

Great! Yes, I will move the VARBC table setting and all satellite bias related folder/files to config/satbiasdata.csh and then source this new script where needed

**Comment by jjguerrette** [comment]
Closing for now.  Still some more work to do.

**Comment by jjguerrette** [comment]
@metdyn, please do not push files to this PR.  Please submit a separate PR with the FAQ file so that it can be developed separately.

**Comment by jjguerrette** [comment]
@metdyn, I think the updated `README.md` provides a better description than before.  It is also enhanced with GitHub Markup.

**Comment by metdyn** [comment]
I tested 3denvar-60-iter_OIE120km_WarmStart on Cheyenne. The cycle experiment runs well and I get  CyclingDA/2018041500  2018041506  2018041512 both finish with success (mpas-jedi code build on March-2).

**Comment by jjguerrette** [comment]
> I tested 3denvar-60-iter_OIE120km_WarmStart on Cheyenne. The cycle experiment runs well and I get CyclingDA/2018041500 2018041506 2018041512 both finish with success (mpas-jedi code build on March-2).

Thank you @metdyn for trying it.  If you ever want to test all scenarios, you can execute `./test.csh`.

**Review by liujake — APPROVED** [review]
@jjguerrette I have not done the actual review, but like to approve it in case you want to merge now. Then everyone has a new 'develop' version to play with.

**Comment by jjguerrette** [comment]
> @jjguerrette I have not done the actual review, but like to approve it in case you want to merge now. Then everyone has a new 'develop' version to play with.

OK.  Yes, that's probably best.  The way to set up experiments in this version is very different from before.

**Comment by junmeiban** [comment]
I ran 120km 3denvar successfully by using ncdiag obs. Thanks JJ.

**Review by junmeiban — APPROVED** [review]

**Comment by jjguerrette** [comment]
@syha, if the merge into your IAU branch is not straightforward, please ask me to do it.  I expect that many of the files you are touching are modified in this PR.

**Pull request merged**
