### PR TITLE
Extended forecasts from external analyses

### LINKED ISSUE #192: Run cold-start extended forecasts
E.g., from GFS analyses.  Will want to be able to run from any kind of `externalanalyses` in the future.

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
Adds a scenario (`ForecastFromGFSAnalyses`) that runs cold-start forecasts from GFS analyses.  This is added as an `elif` branch in `drive.csh`.  A later PR will move this functionality to its own suite and enable verification steps after each forecast completes.

### Issue closed

Closes #192 

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3dvar_O30kmIE60km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

### CODE REVIEW

**Comment by ibanos90** [comment]
Hi @jjguerrette, thanks for this PR! I am trying to run the tests as well as a test for the new scenario added, but it seems like a job running in the background uses an excessive amount of the total available CPU resources and I am kicked out of the login node which kills the jobs submitted in that node. Does this happen to you as well?

**Comment by jjguerrette** [comment]
Yes @ibanos90, that happened to me too for the `ForecastFromGFSAnalyses` scenario.  I must have something wrong, because I  was not intending to run anything in the background.  I'm a little busy with something else this week, but might get back to this PR soon.  This development is a bit old, so I have not tested it in a while.  The same scenario works fine in `feature/1_pythonConfigParse`.

**Comment by ibanos90** [comment]
> Yes @ibanos90, that happened to me too for the `ForecastFromGFSAnalyses` scenario. I must have something wrong, because I was not intending to run anything in the background. I'm a little busy with something else this week, but might get back to this PR soon. This development is a bit old, so I have not tested it in a while. The same scenario works fine in `feature/1_pythonConfigParse`.

Thanks for letting me know. I noticed that the BATCH settings were not inherited in the `ExtendedFCFromExternalAnalysis` task along with ExtendedFCBase. After adding it, the task gets submitted and the test passes.

**Comment by jjguerrette** [comment]
Thank you @ibanos90!  Your suggestion was very helpful.

**Review by ibanos90 — APPROVED** [review]
All test passed along with the test for the new scenario. Thanks for the changes in this PR!

**Comment by jjguerrette** [comment]
Thank you for running those tests @ibanos90.  Hopefully this feature is useful for you.  I'm going to check the boxes based on your feedback, then merge.

**Pull request merged**
