### PR TITLE
Move config/modeldata.csh functionality to YAML

### LINKED ISSUE #115: Deprecate config/modeldata.csh
Move the functionality achieved in `config/modeldata.csh` to YAML so that new model state data sources (ensemble forecasts for covariances, initial background states, external analyses, e.g., from GFS) can be more easily integrated.  This is the first step to moving the workflow beyond its heavy usage of PANDAC archive data for 2018, similar to what is already available for observations.

Work is mostly complete in ~~`feature/modeldata2yaml`~~ `feature/1_modeldata2yaml` with base branch `feature/scenarioConfigCleanup`.

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
Big set of changes to get the last of our model-space data selections into scenario YAMLS.  Presently there are three kinds of model-space data ingested or created by the workflow.  Their selection was controlled by five parameters (`InitializationType`, `model.AnalysisSource`, `model.fixedEnsBSource`, `model.nPreviousEnsDAMembers`, and `model.PreviousEDAForecastDir`).  Those somewhat vague options are replaced by three `resource` selections, where the `resource` options are pulled from an extensible library of user-defined options.

1. `variational.ensemble.forecasts.resource` with available options:
  a. `PANDAC.GEFS` (can be used only for 20180415T00-20180514T18; 120km and 60km ensembleMesh)
  b. `PANDAC.DART` (can be used only for 20180415T00-20180514T018; 60km ensembleMesh) 
  c. `PANDAC.EDΑ` (can be used only for 20180415T00-20180514T18; 60km ensembleMesh)
  d. `None` --> only valid for stochastic cycling, i.e., when `firstbackground.nMembers` > 1

3. `firstbackground.resource` with available options:
  a. `ForecastFromAnalysis` (same as old `ColdStart` `InitializationType`)
  b. `PANDAC.GFS` (same as old `WarmStart` `InitializationType` when `nMembers`==1)
  c. `PANDAC.LaggedGEFS` (same as old `WarmStart` `InitializationType` when `nMembers`>1)

4. `externalanalyses.resource` replacing `model.AnalysisSource` with available options:
  a. `GFS.PANDAC` (can be used only for 20180415T00-20180525T00 and 120km, 60km, and 30km meshes)
  b. `GFS.RDA` (can be used in any experiment where RDA data exists)
  c. `GFS.NCEPFTP` (used in real-time experiments or where NCEP FTP data exists)

Examples for each possible option are given in the canned scenario YAMLS (`scenarios/*.yaml`).  There is a new option (`firstbackground.nMembers`), which automatically switches between deterministic (single-member) and stochastic (multi-member) cycling.  Note that `firstbackground.resource.{{outerMesh}}.{{maxMembers}}` must be larger than 1 in order to run stochastic cycling.

For more info on the user-interface changes, refer to the differences in the following base scenario files:
 - `scenarios/base/variational.yaml`
 - `scenarios/base/firstbackground.yaml`
 - `scenarios/base/externalanalyses.yaml`

Many script and cylc tasks names are changed to reflect the latest functionality that they provide.  Overall, it should be easier than before to add new sources of offline-generated data and to extend the workflow to handle new methods of auto-generating data (e.g., `firstbackground` ensembles).

### Blocking PR

This PR is targeting `feature/scenarioConfigCleanup`.  #114 should be merged before this PR.

### Issue closed

Closes #115

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

### CODE REVIEW

**Review by ibanos90 — APPROVED** [review]
Very nice changes! Thanks @jjguerrette. Ran the tests and all completed successfully.

**Comment by jjguerrette** [comment]
Thanks @ibanos90!  I will wait to merge this one until after IAU is merged to avoid causing any more merge headaches for @syha.  It is not a rush to merge this work, but it may be helpful for others outside of our group who want to use an ensemble during a non-PANDAC period.

**Comment by ibanos90** [comment]
> Thanks @ibanos90! I will wait to merge this one until after IAU is merged to avoid causing any more merge headaches for @syha. It is not a rush to merge this work, but it may be helpful for others outside of our group who want to use an ensemble during a non-PANDAC period.

Sounds good!

**Comment by jjguerrette** [comment]
@syha, I updated `/forecast.csh` to simplify some of the logic.  Currently I have a test running with `IAU=True` that is in the third cycle.  IAU was activated successfully in the second cycle.  See the directory below if you are curious.

/glade/scratch/guerrett/pandac/guerrett_3denvar-60-iter_OIE120km_IAUfix2

Some follow-on PR's will further simplify some of the first cycle vs. later cycles logic.

@ibanos90 and @syha, I updated your scenario YAMLS to include the new `firstbackground`, `externalanalyses`, and `variational.ensemble.forecasts.resource` settings.

All 5 automated tests finished successfully with the most recent changes, essentially merging in the IAU capability.

**Pull request merged**
