### PR TITLE
Add support for log levels.

### PR DESCRIPTION
**Pull request by jim-p-w**
### Description
Different log levels will result in more or fewer log messages.
The level is controlled by the CYLC_DEBUG environment variable.
A value of 0 has the fewest messages, a value of 3 is the most verbose.
Default value (if CYLC_DEBUG is not set) is level 1.

To set the logging verbosity, before invoking Run.py or test.csh set CYLC_DEBUG
bash: `export CYLC_DEBUG=0`
tcsh: `setenv CYLC_DEBUG 0`

level 1 will show 
```
#########################################################################
Running the scenario: test/testinput/3dvar_OIE120km_WarmStart.yaml
#########################################################################
Experiment: ======================================================================
Experiment: Setting up a new suite
Experiment:   SuiteName: jwittig_3dvar_OIE120km_WarmStart_TEST
Experiment:   mainScriptDir: /glade/derecho/scratch/jwittig/pandac/jwittig_3dvar_OIE120km_WarmStart_TEST/MPAS-Workflow
Experiment:   ExperimentDirectory: /glade/derecho/scratch/jwittig/pandac/jwittig_3dvar_OIE120km_WarmStart_TEST
Experiment: ======================================================================
./submit.csh cylc version: 8.2.2
./submit.csh (INFO): checking if a suite with the same name is already running
./submit.csh cylc install --run-name=jwittig_3dvar_OIE120km_WarmStart_TEST
Valid for cylc-8.2.2

 ▪ ■  Cylc Workflow Engine 8.2.2
 ██   Copyright (C) 2008-2023 NIWA
▝▘    & British Crown (Met Office) & Contributors
```

level 0 will show the same, excluding the `Experiment` lines
level 2 will show similar output you see before this PR.
level 3 will show a little more than level 2.

### Issue closed

Closes #(if applicable)

#### Tier 1:
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_IAU_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3dvar_O30kmIE60km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] 4denvar_OIE120km_WarmStart
 - [x] 4dhybrid_OIE120km_WarmStart
 - [x] eda_OIE120km_WarmStart
 - [x] getkf_OIE120km_WarmStart
 - [ ] ForecastFromGFSAnalysesMPT 
    - This failed due to missing data files for the ExtendedMeanFC steps. File `x1.655362.graph.info.part.128` is missing.

#### Tier 2 (optional):
 - [ ] GenerateGFSAnalyses
 - [ ] GenerateObs

### CODE REVIEW

**Comment by amstokely** [comment]
Looks good to me! I would add type hints to the methods you modified/added, as they make python a lot easier to follow (at least  imo).

**Review by amstokely — APPROVED** [review]

**Review by amstokely — APPROVED** [review]
Looks good to me! I would add type hints to the methods you modified/added, as they make python a lot easier to follow (at least imo).

**Review by ibanos90 — CHANGES_REQUESTED** [review]
This is a very helpful PR! As we talked, it would be good to add to the description how to use/change this variable for the logging level. From the code is wasn't clear how I should specify it. Thanks!

**Comment by jim-p-w** [comment]
I've added some information to the PR description which explains how to set the logging level.

**Comment by ibanos90** [comment]
> I've added some information to the PR description which explains how to set the logging level.

@jim-p-w Thanks for adding the info to the PR description! I tested all the options and it's very helpful to have this option to add or reduce debugging level when submitting the cylc suites. One question though, do we know if this debugging level will also give us more/less info in the cylc-run directory outputs from cylc? Just curious about it.

Another thing, I noted that in the reference tests you mentioned about the graph file missing. This is because is using `/glade/work/liuz/pandac/prepare_mpas/mpas_static_30km` as the path for the `GraphInfoDir` variable, but this folder does not exist anymore. This is also used in `scenarios/VerifyingGFSAnalysesFromRDA.yaml`. I would suggest to remove the path from the scenario yaml files and use the default path for `GraphInfoDir` specified in `data/Model.py`.

We are using graphs from `/glade/work/duda/static_moved_to_campaign`  (in some scenario yamls) and `/glade/campaign/mmm/parc/liuz/pandac_common/static_from_duda` (default path), however, my guess is that we could use just `/glade/campaign/mmm/parc/liuz/pandac_common/static_from_duda`. Can you confirm @liujake? I cannot remember if there was a particular reason why we would keep using `/glade/work/duda/static_moved_to_campaign`

**Comment by jim-p-w** [comment]
@ibanos90 This code change only impacts what is written to the console when starting a scenario.

**Comment by jim-p-w** [comment]
@ibanos90 Regarding the `GraphInfoDir` changes, I would prefer to make those changes under a separate PR, as they aren't related to these logging changes. (I am happy to create that PR after we decide what changes are needed for that.) Should I open an issue for the `GraphInfoDir` changes?

**Comment by ibanos90** [comment]
> @ibanos90 This code change only impacts what is written to the console when starting a scenario.

That was my guess but good to know for sure. Thanks!

**Comment by ibanos90** [comment]
> @ibanos90 Regarding the `GraphInfoDir` changes, I would prefer to make those changes under a separate PR, as they aren't related to these logging changes. (I am happy to create that PR after we decide what changes are needed for that.) Should I open an issue for the `GraphInfoDir` changes?

That would be great! I also noted that we use two different folders for the external analysis. After some info exchange with @liujake, we may want to just use the external analysis under directories such as `/glade/campaign/mmm/parc/liuz/pandac_common/30km/30km_GFSANA_single`. Maybe this could be included in the PR for the GraphInfo path as part of some cleanup/organization.

**Review by ibanos90 — APPROVED** [review]

**Pull request merged**
