### PR TITLE
Add MHS in benchmark experiments

### LINKED ISSUE #232: Add MHS in benchmark experiments
Add MHS in benchmark experiments.
Note: There is no qc filters available in UFO for MHS. We keep using non-bias-corrected or bias-corrected GSI-ncdiag files.

### PR DESCRIPTION
**Pull request by junmeiban**
### Description
Add MHS in benchmark experiments.
Note: There is no qc filters available in UFO for MHS. We keep using non-bias-corrected or bias-corrected GSI-ncdiag files.  And in `scenarios` `3dvar_O30kmIE60km_ColdStart.yaml` and `3dvar_OIE120km_ColdStart.yaml`, we do not assimilate MHS from raw obs (downloaded from RDA)

### Issue closed
Closes https://github.com/NCAR/MPAS-Workflow/issues/232

### Modified and added files:
M     initialize/data/Observations.py
M     scenarios/defaults/observations.yaml
A	config/jedi/ObsPlugs/da/base/mhs_metop-a.yaml
A	config/jedi/ObsPlugs/da/base/mhs_metop-b.yaml
A	config/jedi/ObsPlugs/da/base/mhs_n18.yaml
A	config/jedi/ObsPlugs/da/base/mhs_n19.yaml
A	config/jedi/ObsPlugs/da/bias/mhs_metop-a.yaml
A	config/jedi/ObsPlugs/da/bias/mhs_metop-b.yaml
A	config/jedi/ObsPlugs/da/bias/mhs_n18.yaml
A	config/jedi/ObsPlugs/da/bias/mhs_n19.yaml
A	config/jedi/ObsPlugs/da/filtersWithBias/mhs_metop-a.yaml
A	config/jedi/ObsPlugs/da/filtersWithBias/mhs_metop-b.yaml
A	config/jedi/ObsPlugs/da/filtersWithBias/mhs_n18.yaml
A	config/jedi/ObsPlugs/da/filtersWithBias/mhs_n19.yaml
A	config/jedi/ObsPlugs/da/filters/mhs_n19.yaml
A	config/jedi/ObsPlugs/da/filters/mhs_n18.yaml
A	config/jedi/ObsPlugs/da/filters/mhs_metop-a.yaml
A	config/jedi/ObsPlugs/da/filters/mhs_metop-b.yaml

#### Tier 1:
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dhybrid_O30kmIE60km_SpecifiedEnsemble_VarBC

### CODE REVIEW

**Comment by junmeiban** [comment]
My work dir:
/glade/scratch/jban/pandac/jban_3dvar-60-iter_O120km
/glade/scratch/jban/pandac/jban_3denvar-60-iter_O120km
/glade/scratch/jban/pandac/jban_3dhybrid-60-60-iter_O30kmI60km_ensB-SE80+RTPP70_VarBC

**Comment by byoung-joo** [comment]
Should we add the mhs section to `PANDACArchive` similar to `PANDACArchiveForVarBC` ?

https://github.com/NCAR/MPAS-Workflow/pull/233/files#diff-df5fd45367880532abf104e0067873ee8ad5cb7b2d8a871b3809dead2ece9f14R80

**Comment by junmeiban** [comment]
> Should we add the mhs section to `PANDACArchive` similar to `PANDACArchiveForVarBC` ?
> 
> https://github.com/NCAR/MPAS-Workflow/pull/233/files#diff-df5fd45367880532abf104e0067873ee8ad5cb7b2d8a871b3809dead2ece9f14R80

Thanks @byoung-joo 's comment. I already added mhs section in `initialize/data/Observations.py`, so do not need to add mhs in `PANDACArchive`.  In `PANDACArchiveForVarBC`, I added the four lines just for bias correction.

**Comment by junmeiban** [comment]
I will add MHS yamls under config/jedi/ObsPlugs/da/filters.

**Comment by byoung-joo** [comment]
Thank you for clarifying that, @junmeiban .
So `instrumentsAllowingBiasCorrection` in `scenarios/defaults/observations.yaml` makes the sensor include VarBC, and `benchmarkObservations` in `initialize/data/Observations.py` specifies the observations to be assimilated!

**Review by byoung-joo — APPROVED** [review]
Looks good to me.

**Pull request merged**
