### PR TITLE
Updated localization matrix and build version

### PR DESCRIPTION
**Pull request by jjguerrette**
Updates needed to use the workflow with the BUMP changes corresponding to https://github.com/JCSDA-internal/mpas-jedi/pull/596.

### CODE REVIEW

**Comment by jjguerrette** [comment]
@metdyn, automated cycling tests will fail until this is merged.

**Review by byoung-joo — APPROVED** [review]
This is a necessary change. 
I will move the bumploc directories to `/glade/p/` space later time.

**Comment by jjguerrette** [comment]
@byoung-joo, if you would like to move the data to `/glade/p/` now, I can update the PR.

**Comment by byoung-joo** [comment]
> @byoung-joo, if you would like to move the data to /glade/p/ now, I can update the PR.

Thank you, @jjguerrette
I just copied the bumploc directories in my `scratch` to `/glade/p/mmm/parc/bjung/pandac_common/bumploc`.

**Pull request merged**
