### PR TITLE
Add functionality for cloud direct insertion (SACA)

### PR DESCRIPTION
**Pull request by ibanos90**
### Description
This PR adds the functionality to do cloud direct insertion (SACA) on cold start forecasts and then run forecasts from the SACA analysis (using the `ExtendedForecast` tasks). A new suite is added for this capability. The default is doing SACA analysis on the 0-hr forecast from a cold start forecast initialized from GFS analysis, but it can be done on the 6-hr as well by changing the variable `prevBgHR`. This variable is used to trigger the cold forecast at the indicated hour (i.e., at the same hour as the SACA analysis (e.g., 00Z), or 6 hours before (e.g., 18Z)). SACA analysis uses a similar approach as the `ExtendedForecast`, thus it does the SACA analysis at the specified mean times. Sea surface fields are updated from the GFS analysis during the `ExtendedForecast` step. The path for the build code is updated.

This PR also includes a fix for the `Concatenate` task so the verification of observations waits until the observations output have been concatenated.

### Issue closed
None

#### Tier 1:
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_IAU_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3dvar_O30kmIE60km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] 4denvar_OIE120km_WarmStart
 - [x] 4dhybrid_OIE120km_WarmStart
 - [x] eda_OIE120km_WarmStart
 - [x] getkf_OIE120km_WarmStart
 - [x] ForecastFromGFSAnalysesMPT 

#### Tier 3 (optional):
 - [x] ForecastFromGFSAnalysesVariableMesh.yaml
 - [x] CloudDirectInsertion.yaml

### CODE REVIEW

**Comment by byoung-joo** [comment]
Thanks for adding this new suite, @ibanos90. I have two quick suggestions as follow.

1. simpler streams
In `config/mpas/saca/streams.atmosphere`, we do not need `background`, `analysis`, `ensemble`, and `control` streams. So we can remove `config/mpas/saca/stream_list.atmosphere.analysis`, `config/mpas/saca/stream_list.atmosphere.background`, `config/mpas/saca/stream_list.atmosphere.control`, `config/mpas/saca/stream_list.atmosphere.ensemble` files and related lines from [bin/SACA.csh](https://github.com/NCAR/MPAS-Workflow/pull/305/files#diff-63778564c5e83d8f4a20604a955b31bc93fc107f3a0c55fb7d2da71820e91933R141-R152)
Also, we can add these variables directly to `config/mpas/saca/stream_list.atmosphere.analysis`.

2. `config/jedi/applications/saca.yaml`
We can delete [this section](https://github.com/NCAR/MPAS-Workflow/pull/305/files#diff-c954a5fbab876c563e34733b4ba6b2429b8a6dda0b33768c3858c6c97f78e33bR1-R7 ), which writes out TEST log and does the comparison between TEST and REF, `config/jedi/refFiles/saca.ref`, and `config/jedi/refFiles/saca.run.ref`. Also from [here](https://github.com/NCAR/MPAS-Workflow/pull/305/files#diff-63778564c5e83d8f4a20604a955b31bc93fc107f3a0c55fb7d2da71820e91933R227-R229).

**Comment by ibanos90** [comment]
> Thanks for adding this new suite, @ibanos90. I have two quick suggestions as follow.
> 
> 1. simpler streams
>    In `config/mpas/saca/streams.atmosphere`, we do not need `background`, `analysis`, `ensemble`, and `control` streams. So we can remove `config/mpas/saca/stream_list.atmosphere.analysis`, `config/mpas/saca/stream_list.atmosphere.background`, `config/mpas/saca/stream_list.atmosphere.control`, `config/mpas/saca/stream_list.atmosphere.ensemble` files and related lines from [bin/SACA.csh](https://github.com/NCAR/MPAS-Workflow/pull/305/files#diff-63778564c5e83d8f4a20604a955b31bc93fc107f3a0c55fb7d2da71820e91933R141-R152)
>    Also, we can add these variables directly to `config/mpas/saca/stream_list.atmosphere.analysis`.
> 2. `config/jedi/applications/saca.yaml`
>    We can delete [this section](https://github.com/NCAR/MPAS-Workflow/pull/305/files#diff-c954a5fbab876c563e34733b4ba6b2429b8a6dda0b33768c3858c6c97f78e33bR1-R7), which writes out TEST log and does the comparison between TEST and REF, `config/jedi/refFiles/saca.ref`, and `config/jedi/refFiles/saca.run.ref`. Also from [here](https://github.com/NCAR/MPAS-Workflow/pull/305/files#diff-63778564c5e83d8f4a20604a955b31bc93fc107f3a0c55fb7d2da71820e91933R227-R229).

Hi @byoung-joo, thanks a lot for taking a look at these changes! I followed your suggestions and made corresponding changes. Could you give it another look if possible? Please let me know if there is anything else that can be improved. Thanks!

**Comment by byoung-joo** [comment]
Thanks for the latest commit, @ibanos90.

Because the stream_list is modified with optional saca diagnostics, would it be better to use `cp` rather than `ln` here ? https://github.com/NCAR/MPAS-Workflow/blob/e0746d6d26098c6d426824a6f2c89c9e9917cf0d/bin/SACA.csh#L156-L159

**Comment by ibanos90** [comment]
> Thanks for the latest commit, @ibanos90.
> 
> Because the stream_list is modified with optional saca diagnostics, would it be better to use `cp` rather than `ln` here ?
> 
> https://github.com/NCAR/MPAS-Workflow/blob/e0746d6d26098c6d426824a6f2c89c9e9917cf0d/bin/SACA.csh#L156-L159

That's a good point. Will change it. Thanks BJ!

**Comment by RGNystrom** [comment]
@ibanos90 I ran the suite of test scenarios this afternoon and received numerous warnings about the walltime being exceeded, e.g., 
`Aborted by PBS Server
Job exceeded resource walltime
See job standard error file`

It is not clear from your changes why the walltime would need to be increased but increasing it appeared to fix this issue. It is also possible this is indicative of a larger derecho issue.

**Comment by RGNystrom** [comment]
> @ibanos90 I ran the suite of test scenarios this afternoon and received numerous warnings about the walltime being exceeded, e.g., `Aborted by PBS Server Job exceeded resource walltime See job standard error file`
> 
> It is not clear from your changes why the walltime would need to be increased but increasing it appeared to fix this issue. It is also possible this is indicative of a larger derecho issue.

Resubmitted the test scenarios this morning and did not notice these anymore. I am increasingly suspicious it was a derecho issue yesterday.

**Comment by ibanos90** [comment]
> > @ibanos90 I ran the suite of test scenarios this afternoon and received numerous warnings about the walltime being exceeded, e.g., `Aborted by PBS Server Job exceeded resource walltime See job standard error file`
> > It is not clear from your changes why the walltime would need to be increased but increasing it appeared to fix this issue. It is also possible this is indicative of a larger derecho issue.
> 
> Resubmitted the test scenarios this morning and did not notice these anymore. I am increasingly suspicious it was a derecho issue yesterday.

Thanks so much for running these tests @RGNystrom! That's very helpful. I agree, it's likely that the issue could be related to derecho. I am glad it works today.

**Review by byoung-joo — APPROVED** [review]
I have tried this branch for my own testing last week.
Various DI-related configurations worked as intended. One thing I didn't try is ... applying DI to 6hr (for example) forecast field as background.

**Comment by ibanos90** [comment]
> I have tried this branch for my own testing last week. Various DI-related configurations worked as intended. One thing I didn't try is ... applying DI to 6hr (for example) forecast field as background.

Thanks @byoung-joo!

**Pull request merged**
