### PR TITLE
Enable previous EDA forecasts to be used in 3denvar experiment

### PR DESCRIPTION
**Pull request by jjguerrette**
For an example, see `/glade/scratch/guerrett/pandac/guerrett_3denvar_OIE120km_PreviousEDALeave20`.

### CODE REVIEW

**Comment by junmeiban** [comment]
Thanks @jjguerrette for adding this function,  I can run 3denvar by using your members:  
```
/glade/scratch/guerrett/pandac/guerrett_eda_3denvar_NMEM20_LeaveOneOut_OIE120km/CyclingFC/*****/mem****/mpasout.yyyy-mm-dd_hh.00.00.nc.
```
But if I switch to run “eda_3denvar” (setenv DAType eda_3denvar) using the same workflow, I got failure info: 
```
/glade/scratch/jban/cylc-run/jban_eda_3denvar_NMEM20_LeaveOneOut_OIE120km/log/job/20180415T0000-06/CyclingDA/02/job.out
fixedEnsBType: Undefined variable.
```
Am I missing something in the setting?

**Comment by jjguerrette** [comment]
> But if I switch to run “eda_3denvar” (setenv DAType eda_3denvar) using the same workflow, I got failure info:
> 
> ```
> /glade/scratch/jban/cylc-run/jban_eda_3denvar_NMEM20_LeaveOneOut_OIE120km/log/job/20180415T0000-06/CyclingDA/02/job.out
> fixedEnsBType: Undefined variable.
> ```

Thank you for testing Junmei!  I only tested 3denvar, but should have also tested eda_3denvar.  Will fix this soon then push changes.

**Comment by junmeiban** [comment]
@jjguerrette , thank you. Both of 3denvar and eda_3denvar work now.

**Review by junmeiban — APPROVED** [review]
@jjguerrette , thank you. Both of 3denvar and eda_3denvar

**Pull request merged**
