### PR TITLE
Consolidate YAML parsing functions

### LINKED ISSUE #113: Consolidate YAML parsing functions
All `config/*.csh` scripts that parse YAML files include a header defining functions that do the parsing.  The functions are functionally identical for all YAML sections (i.e., all csh scripts).  Move the function definition to `config/scenarios.csh` and add ample user documentation.

This work is located in `feature/scenarioConfigCleanup`.

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description

YAML parsing function definition is centrally located to `config/scenario.csh` instead of being duplicated in many scripts.

### Issue closed

Closes #113

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

### CODE REVIEW

**Comment by jjguerrette** [comment]
Completed tests a long time ago; re-running now with develop merge

**Comment by jjguerrette** [comment]
> Completed tests a long time ago; re-running now with develop merge

All tests passed.  Wait to merge until after #105.

**Comment by jjguerrette** [comment]
> > Completed tests a long time ago; re-running now with develop merge
> 
> All tests passed. Wait to merge until after #105.

Actually, I just checked and there are no conflicts with `feature/iau`.  So this PR can be merged after approval.

**Review by ibanos90 — APPROVED** [review]
Thanks for these changes to the workflow @jjguerrette! Ran the tests and all completed successfully.

**Pull request merged**
