### PR TITLE
Move mesh-specific settings to application-specific YAMLS

### LINKED ISSUE #72: Incorporate mesh-specific settings into YAMLs
Follow-on to #68.  Move the settings under `config/mpas/O*IE*/mesh.csh` and `config/mpas/O*IE*/job.csh` to yaml files to improve user-configurability.  Those might get placed under the `model` section of the yaml.  One possibility is to create files like `scenarios/mesh/OIE120km.yaml`, `scenarios/mesh/OIE60km.yaml`, etc... that automatically get selected based on `model.MPASGridDescriptor`.  Then those settings would get parsed within `config/model.csh`.

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
Multiple thrusts of re-organization are executed in this PR.

1. Global settings that resided in `config/filestructure.csh` are controlled by a new script, `generateExperimentConfig.csh`, which automatically generates `config/experiment.csh`.  This avoids `config/experiment.csh`, which sets up the experiment directory structure, needing to source `variational`, `model`, and `rtpp` settings every time it is sourced.  The experiment directory name is fixed after all.  

2. Multiple templated (sed-substituted) variables in `PrepJEDI.csh` are replaced with command-line arguments.  The new `ArgAppType` variable is enough to determine both the `AppName` and the `AppType`, which were previously sed-substituted variables.  `tasks.rc` is modified to send the appropriate application type to `PrepJEDI.csh` when it is executed.  This is a first step in removing templating from `PrepJEDI.csh`, which is not really needed.  Command-line arguments will be used to replace other templated variables across applications in follow-on PR's.  The goal is this effort is to eventually have each application (e.g., `variational`, `hofx`, etc...) be fully self-determined.  This makes application-specific testing and development easier, and it is the first step necessary to migrate those applications to python classes.

3. All mesh-dependent settings formerly located in `config/mpas/O*IE*.csh` are moved to application-specific yamls under `scenarios/base/*.yaml`.  The former `MPASGridDescriptor` is replaced by three independent settings, `outerMesh`, `innerMesh`, and `ensembleMesh` (e.g., 30km, 60km, and 120km).  These are used to drive the resource specifications in the application YAMLS.  For example, `variational.yaml` includes `localization`, `covariance`, and `job` sections, for which excerpts are shown below.

```yaml
  localization:
    #{{ensembleMesh}}:
    #  bumpLocPrefix: str
    #  bumpLocDir: str
    120km:
      bumpLocPrefix: bumploc_1200.0km_6.0km
      bumpLocDir: /glade/p/mmm/parc/guerrett/pandac/fixed_input/120km/bumploc/h=1200.0km_v=6.0km_16MAR2022code

  covariance:
    #{{innerMesh}}:
    #  bumpCovDir: str
    #  bumpCovStdDevFile: str
    #  bumpCovVBalDir: str
    120km:
      bumpCovDir: /glade/scratch/bjung/pandac/20220307_develop/bumpcov_tune
      bumpCovStdDevFile: /glade/scratch/bjung/pandac/20220307_develop/CMAT_00.tune/mpas.stddev.2018-04-15_00.00.00.nc
      bumpCovVBalDir: /glade/scratch/bjung/pandac/20220307_develop/bumpcov_tune

  job:
    #{{outerMesh}}:
    #  {{innerMesh}}:
    #    {{baseDAType}}: # i.e., 3dvar, 3denvar, 3dhybrid, 4denvar, etc...
    #      baseSeconds: int
    #      secondsPerEnVarMember: int, default is 0
    #      #@ seconds = $secondsPerEnVarMember * $nEnVarMembers + $baseSeconds
    #      nodes: int
    #      PEPerNode: int
    #      memory: int
    30km:
      30km:
        3denvar:
          baseSeconds: 1500
          secondsPerEnVarMember: 5
          nodes: 64
          PEPerNode: 8
          memory: 45
        3dvar:
          baseSeconds: 1500
          nodes: 64
          PEPerNode: 8
          memory: 45
      60km:
        3denvar:
          baseSeconds: 1200
          secondsPerEnVarMember: 10
          nodes: 6
          PEPerNode: 32
          memory: 109
        3dvar:
          baseSeconds: 1200
          nodes: 6
          PEPerNode: 32
          memory: 109
```

Note that `3dvar` and `3denvar` can have different resource requirements.  `forecast`, `hofx`, `rtpp`, `verifymodel`, `verifyobs`, `initic`, and `ensvariational` applications also have mesh-dependent job resource settings.  In this way a user/developer who only wants to evaluate `variational` for computational or algorithm changes does not need to consider the settings for other applications as they formerly did with the old configuration method.

### Issue closed

Closes #72

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

### CODE REVIEW

**Comment by jjguerrette** [comment]
Making some changes.  Will reopen when ready.

**Comment by jjguerrette** [comment]
For the time being, I needed to increase the wall-time of obs-space verification after Variational.  There are many added channels for AMSUA (1-15 instead of only a subset) in the output files, which has increased the total time.  Either the diagnostic scripts or the workflow need to be cleaned up to remove diagnostics calculation for unassimilated channels.

**Review by ibanos90 — APPROVED** [review]
These changes are very nice! Thanks @jjguerrette.
Ran the tests and all completed successfully.

**Comment by jjguerrette** [comment]
I will resolve the conflicts with the latest develop before merging.  Maybe by Friday.

**Pull request merged**
