### PR TITLE
OIE60km EDA and dual-mesh O30kmIE60km single-state 3denvar

### LINKED ISSUE #37: Enable 60km experiments
Single-mesh eda_3denvar: OIE60km
Dual-mesh 3denvar: O30kmIE60km

### PR DESCRIPTION
**Pull request by jjguerrette**
Enables 60km cycling experiments and dual-mesh cycling experiments with 30km outer loop and forecasts and 60km inner loop and ensembles

Closes #37

### CODE REVIEW

**Comment by jjguerrette** [comment]
Note: these are very expensive setups to run.  If OIE60km is to be tested for eda_3denvar, very few ensemble members should be tested.  There are benchmark timing results under `config/mpas/OIE60km/job.csh` for reference when using more ensemble members.

**Comment by ibanos90** [comment]
For this PR#38 (branch feature/OIE60km-O30kmIE60km) I ran two experiments (one cycle): 
**OIE60km: eda_3denvar (5 members)** ==> VerifyModelBG5 job ran successfully, but for the other 4 members the same jobs failed due to walltime limit (VerifyModelJobMinutes 5).
**O30kmIE60km: 3denvar** ==> VerifyModelBG1 job failed due to walltime limit (VerifyModelJobMinutes 20).

I ran more two experiments using the branch develop with OIE120km (one cycle):
**OIE120km: 3denvar** ==> all jobs completed successfully  (VerifyModelJobMinutes 2)
**OIE120km: eda_3denvar (5 members)** ==> most VerifyModelBG* jobs for each member failed due to walltime limit.
I increased the walltime for these jobs to 3, 4, 5, 10, 20, and 30 minutes and most jobs continue to fail each time. However, since some succeed I am not sure what can be the issue here.

Note that when VerifyModelBG* jobs failed, there is the following error message in the corresponding job.out file:
python writediagstats_modelspace.py 2018041500 -r /glade/p/mmm/parc/liuz/pandac_common/120km_GFSANA/x1.40962.init
Error: library 2 not found.
       Run ncar_pylib -l to list valid library names.

The jobs logs can be found at /glade/scratch/ivette/cylc-run/PR38 for the experiments mentioned above:
 ivette_eda_3denvar-60-iter_NMEM5_RTPP0.80_LeaveOneOut_OIE60km
ivette_3denvar-60-iter_O30kmIE60km 
ivette_3denvar-60-iter_OIE120km  
ivette_eda_3denvar-60-iter_NMEM5_RTPP0.80_LeaveOneOut_OIE120km 

You can also check, for example, the log.writediagstats_modelspace file at /glade/scratch/ivette/pandac/PR38/ivette_3denvar-60-iter_O30kmIE60km/Verification/bg/2018041500/diagnostic_stats/model for an experiment were some VerifyModelBG* jobs failed.

**Comment by jjguerrette** [comment]
Thank you @ibanos90 for the comment.  I see similar problems with the develop branch.  So I do not think it is caused by this PR or #39.  It is likely due to the recent changes on Cheyenne of the submit environment not being propagated to the job environment.  We have had problems in the past with python getting loaded properly (using ncar_pylib) in the job environment.  So it was convenient to have python loaded under `env-setup/cheyenne.*`, but that does not work anymore. I will try to figure out a solution, probably using the `-V` flag for `Verify*` jobs as a quick solution.

See here for more info:
https://www2.cisl.ucar.edu/resources/computational-systems/propagating-environment-settings-pbs-job

**Review by ibanos90 — APPROVED** [review]

**Comment by ibanos90** [comment]
Ran the experiments after the changes and all jobs completed successfully. Thanks for the fix!

**Pull request merged**
