### PR TITLE
Add LETKF and LGETKF as EnKF application

### LINKED ISSUE #195: Add EnKF application
Progress is in [feature/letkf](https://github.com/NCAR/MPAS-Workflow/tree/feature/letkf).

The base branch is [feature/1_pythonConfigParse](https://github.com/NCAR/MPAS-Workflow/tree/feature/1_pythonConfigParse).

The feature branch allows for simple substitution of an `enkf` yaml section in place of a comparable `variational` yaml section in an EDA scenario.

E.g., compare these two test yamls: [letkf](https://github.com/NCAR/MPAS-Workflow/blob/feature/letkf/test/testinput/letkf_OIE120km_WarmStart.yaml), [eda](https://github.com/NCAR/MPAS-Workflow/blob/feature/letkf/test/testinput/eda_OIE120km_WarmStart.yaml)

Still working through debugging for the 120km letkf test case.

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
Adds a new EnKF application, within which users can select either the `GETKF` or `LETKF` as `solver`.  The LETKF can use either 2D or 3D localization.  The LGETKF (i.e., `GETKF`) uses a 2D geometry iterator and a modulated ensemble for vertical localization, effectively accomplishing 3D localization.  See the relevant oops, ufo, and mpas-jedi issues and PRs for more info.

Example scenario YAMLS are given in the `scenarios/` directory for 60km EnKF's, and a new test is added that runs 1 cycle of a 5-member 120km GETKF.  The new test is similar to the existing 120km EDA test, with the En-3DEnVar replaced by LGETKF.  That substitution is accomplished by replacing the `variational` section of the scenario YAML with a new `enkf` section.  In the python-based initialization, the `DA` parent application can either instantiate a `Variational` or an `EnKF` object, depending on the scenario yaml.

The large number of modified files in this PR is attributable to the EnKF being split into 2 steps, first the observer, then the solver.  The observer step reads in the original observation files, converted to IODA format, and the solver step reads in the `obsout` files produced from the observer step.  This is accomplished by (1) moving the `ObsPlugs/variational` yamls to a common `da` directory (used by both Variational and EnKF), and (2) modifying `ObsPlugs/da/base/*.yaml` such that the EnKF and Variational applications control the observation file reading and writing via yaml anchors.  EnKF and Variational have their own application-specific `ObsAnchors.yaml`, which allows for the EnKF to switch between RoundRobin and Halo distributions in the observer and solver, respectively, and to apply observation-space localization.

### Issue closed

Closes #195

#### Tier 1:
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3dvar_O30kmIE60km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart
 - [x] getkf_OIE120km_WarmStart

### List of modified files
M	.github/pull_request_template.md
A	bin/CleanEnKF.csh
A	bin/EnKF.csh
A	bin/EnKFObserver.csh
A	bin/InitEnKF.csh
M	bin/InitVariationals.csh
M	bin/PrepJEDI.csh
M	bin/Variational.csh
M	bin/getCycleVars.csh
R077	config/jedi/ObsPlugs/variational/base/abi-clr_g16.yaml	config/jedi/ObsPlugs/da/base/abi-clr_g16.yaml
R077	config/jedi/ObsPlugs/variational/base/abi_g16.yaml	config/jedi/ObsPlugs/da/base/abi_g16.yaml
R077	config/jedi/ObsPlugs/variational/base/ahi-clr_himawari8.yaml	config/jedi/ObsPlugs/da/base/ahi-clr_himawari8.yaml
R078	config/jedi/ObsPlugs/variational/base/ahi_himawari8.yaml	config/jedi/ObsPlugs/da/base/ahi_himawari8.yaml
R076	config/jedi/ObsPlugs/variational/base/aircraft.yaml	config/jedi/ObsPlugs/da/base/aircraft.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua-cld_aqua.yaml	config/jedi/ObsPlugs/da/base/amsua-cld_aqua.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua-cld_metop-a.yaml	config/jedi/ObsPlugs/da/base/amsua-cld_metop-a.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua-cld_metop-b.yaml	config/jedi/ObsPlugs/da/base/amsua-cld_metop-b.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua-cld_n15.yaml	config/jedi/ObsPlugs/da/base/amsua-cld_n15.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua-cld_n18.yaml	config/jedi/ObsPlugs/da/base/amsua-cld_n18.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua-cld_n19.yaml	config/jedi/ObsPlugs/da/base/amsua-cld_n19.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua_aqua.yaml	config/jedi/ObsPlugs/da/base/amsua_aqua.yaml
R078	config/jedi/ObsPlugs/variational/base/amsua_metop-a.yaml	config/jedi/ObsPlugs/da/base/amsua_metop-a.yaml
R078	config/jedi/ObsPlugs/variational/base/amsua_metop-b.yaml	config/jedi/ObsPlugs/da/base/amsua_metop-b.yaml
R078	config/jedi/ObsPlugs/variational/base/amsua_metop-c.yaml	config/jedi/ObsPlugs/da/base/amsua_metop-c.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua_n15.yaml	config/jedi/ObsPlugs/da/base/amsua_n15.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua_n18.yaml	config/jedi/ObsPlugs/da/base/amsua_n18.yaml
R077	config/jedi/ObsPlugs/variational/base/amsua_n19.yaml	config/jedi/ObsPlugs/da/base/amsua_n19.yaml
R074	config/jedi/ObsPlugs/variational/base/gnssroref.yaml	config/jedi/ObsPlugs/da/base/gnssroref.yaml
R096	config/jedi/ObsPlugs/variational/base/iasi_metop-a.yaml	config/jedi/ObsPlugs/da/base/iasi_metop-a.yaml
R096	config/jedi/ObsPlugs/variational/base/iasi_metop-b.yaml	config/jedi/ObsPlugs/da/base/iasi_metop-b.yaml
R096	config/jedi/ObsPlugs/variational/base/iasi_metop-c.yaml	config/jedi/ObsPlugs/da/base/iasi_metop-c.yaml
R076	config/jedi/ObsPlugs/variational/base/satwind.yaml	config/jedi/ObsPlugs/da/base/satwind.yaml
R066	config/jedi/ObsPlugs/variational/base/satwnd.yaml	config/jedi/ObsPlugs/da/base/satwnd.yaml
R064	config/jedi/ObsPlugs/variational/base/sfc.yaml	config/jedi/ObsPlugs/da/base/sfc.yaml
R066	config/jedi/ObsPlugs/variational/base/sondes-2018043006.yaml	config/jedi/ObsPlugs/da/base/sondes-2018043006.yaml
R067	config/jedi/ObsPlugs/variational/base/sondes.yaml	config/jedi/ObsPlugs/da/base/sondes.yaml
R100	config/jedi/ObsPlugs/variational/bias/abi_g16.yaml	config/jedi/ObsPlugs/da/bias/abi_g16.yaml
R100	config/jedi/ObsPlugs/variational/bias/ahi_himawari8.yaml	config/jedi/ObsPlugs/da/bias/ahi_himawari8.yaml
R100	config/jedi/ObsPlugs/variational/bias/amsua_aqua.yaml	config/jedi/ObsPlugs/da/bias/amsua_aqua.yaml
R100	config/jedi/ObsPlugs/variational/bias/amsua_metop-a.yaml	config/jedi/ObsPlugs/da/bias/amsua_metop-a.yaml
R100	config/jedi/ObsPlugs/variational/bias/amsua_metop-b.yaml	config/jedi/ObsPlugs/da/bias/amsua_metop-b.yaml
R100	config/jedi/ObsPlugs/variational/bias/amsua_metop-c.yaml	config/jedi/ObsPlugs/da/bias/amsua_metop-c.yaml
R100	config/jedi/ObsPlugs/variational/bias/amsua_n15.yaml	config/jedi/ObsPlugs/da/bias/amsua_n15.yaml
R100	config/jedi/ObsPlugs/variational/bias/amsua_n18.yaml	config/jedi/ObsPlugs/da/bias/amsua_n18.yaml
R100	config/jedi/ObsPlugs/variational/bias/amsua_n19.yaml	config/jedi/ObsPlugs/da/bias/amsua_n19.yaml
R100	config/jedi/ObsPlugs/variational/bias/iasi_metop-a.yaml	config/jedi/ObsPlugs/da/bias/iasi_metop-a.yaml
R100	config/jedi/ObsPlugs/variational/bias/iasi_metop-b.yaml	config/jedi/ObsPlugs/da/bias/iasi_metop-b.yaml
R100	config/jedi/ObsPlugs/variational/bias/iasi_metop-c.yaml	config/jedi/ObsPlugs/da/bias/iasi_metop-c.yaml
R100	config/jedi/ObsPlugs/variational/filters/abi-clr_g16.yaml	config/jedi/ObsPlugs/da/filters/abi-clr_g16.yaml
R100	config/jedi/ObsPlugs/variational/filters/abi_g16.yaml	config/jedi/ObsPlugs/da/filters/abi_g16.yaml
R100	config/jedi/ObsPlugs/variational/filters/ahi-clr_himawari8.yaml	config/jedi/ObsPlugs/da/filters/ahi-clr_himawari8.yaml
R100	config/jedi/ObsPlugs/variational/filters/ahi_himawari8.yaml	config/jedi/ObsPlugs/da/filters/ahi_himawari8.yaml
R100	config/jedi/ObsPlugs/variational/filters/aircraft.yaml	config/jedi/ObsPlugs/da/filters/aircraft.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua-cld_aqua.yaml	config/jedi/ObsPlugs/da/filters/amsua-cld_aqua.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua-cld_metop-a.yaml	config/jedi/ObsPlugs/da/filters/amsua-cld_metop-a.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua-cld_metop-b.yaml	config/jedi/ObsPlugs/da/filters/amsua-cld_metop-b.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua-cld_n15.yaml	config/jedi/ObsPlugs/da/filters/amsua-cld_n15.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua-cld_n18.yaml	config/jedi/ObsPlugs/da/filters/amsua-cld_n18.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua-cld_n19.yaml	config/jedi/ObsPlugs/da/filters/amsua-cld_n19.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua_aqua.yaml	config/jedi/ObsPlugs/da/filters/amsua_aqua.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua_metop-a.yaml	config/jedi/ObsPlugs/da/filters/amsua_metop-a.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua_metop-b.yaml	config/jedi/ObsPlugs/da/filters/amsua_metop-b.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua_metop-c.yaml	config/jedi/ObsPlugs/da/filters/amsua_metop-c.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua_n15.yaml	config/jedi/ObsPlugs/da/filters/amsua_n15.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua_n18.yaml	config/jedi/ObsPlugs/da/filters/amsua_n18.yaml
R100	config/jedi/ObsPlugs/variational/filters/amsua_n19.yaml	config/jedi/ObsPlugs/da/filters/amsua_n19.yaml
R100	config/jedi/ObsPlugs/variational/filters/gnssroref.yaml	config/jedi/ObsPlugs/da/filters/gnssroref.yaml
R100	config/jedi/ObsPlugs/variational/filters/iasi_metop-a.yaml	config/jedi/ObsPlugs/da/filters/iasi_metop-a.yaml
R100	config/jedi/ObsPlugs/variational/filters/iasi_metop-b.yaml	config/jedi/ObsPlugs/da/filters/iasi_metop-b.yaml
R100	config/jedi/ObsPlugs/variational/filters/iasi_metop-c.yaml	config/jedi/ObsPlugs/da/filters/iasi_metop-c.yaml
R100	config/jedi/ObsPlugs/variational/filters/satwind.yaml	config/jedi/ObsPlugs/da/filters/satwind.yaml
R100	config/jedi/ObsPlugs/variational/filters/satwnd.yaml	config/jedi/ObsPlugs/da/filters/satwnd.yaml
R100	config/jedi/ObsPlugs/variational/filters/sfc.yaml	config/jedi/ObsPlugs/da/filters/sfc.yaml
R100	config/jedi/ObsPlugs/variational/filters/sondes-2018043006.yaml	config/jedi/ObsPlugs/da/filters/sondes-2018043006.yaml
R100	config/jedi/ObsPlugs/variational/filters/sondes.yaml	config/jedi/ObsPlugs/da/filters/sondes.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/abi_g16.yaml	config/jedi/ObsPlugs/da/filtersWithBias/abi_g16.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/ahi_himawari8.yaml	config/jedi/ObsPlugs/da/filtersWithBias/ahi_himawari8.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/amsua_aqua.yaml	config/jedi/ObsPlugs/da/filtersWithBias/amsua_aqua.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/amsua_metop-a.yaml	config/jedi/ObsPlugs/da/filtersWithBias/amsua_metop-a.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/amsua_metop-b.yaml	config/jedi/ObsPlugs/da/filtersWithBias/amsua_metop-b.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/amsua_metop-c.yaml	config/jedi/ObsPlugs/da/filtersWithBias/amsua_metop-c.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/amsua_n15.yaml	config/jedi/ObsPlugs/da/filtersWithBias/amsua_n15.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/amsua_n18.yaml	config/jedi/ObsPlugs/da/filtersWithBias/amsua_n18.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/amsua_n19.yaml	config/jedi/ObsPlugs/da/filtersWithBias/amsua_n19.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/iasi_metop-a.yaml	config/jedi/ObsPlugs/da/filtersWithBias/iasi_metop-a.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/iasi_metop-b.yaml	config/jedi/ObsPlugs/da/filtersWithBias/iasi_metop-b.yaml
R100	config/jedi/ObsPlugs/variational/filtersWithBias/iasi_metop-c.yaml	config/jedi/ObsPlugs/da/filtersWithBias/iasi_metop-c.yaml
A	config/jedi/ObsPlugs/enkf/ObsAnchors.yaml
M	config/jedi/ObsPlugs/variational/ObsAnchors.yaml
A	config/jedi/applications/enkf.yaml
A	config/mpas/enkf/namelist.atmosphere
A	config/mpas/enkf/stream_list.atmosphere.analysis
A	config/mpas/enkf/stream_list.atmosphere.background
A	config/mpas/enkf/stream_list.atmosphere.control
A	config/mpas/enkf/stream_list.atmosphere.ensemble
A	config/mpas/enkf/streams.atmosphere
M	initialize/applications/DA.py
A	initialize/applications/EnKF.py
M	initialize/applications/Variational.py
M	initialize/config/Task.py
M	initialize/data/Observations.py
M	initialize/framework/Build.py
M	initialize/framework/Experiment.py
M	initialize/framework/HPC.py
M	initialize/framework/Naming.py
M	initialize/suites/Cycle.py
M	scenarios/3denvar_O30kmIE60km_WarmStart.yaml
M	scenarios/3denvar_O30kmIE60km_WarmStart_ABEI.yaml
M	scenarios/3denvar_O30kmIE60km_WarmStart_SpecifiedEnsemble.yaml
M	scenarios/3dhybrid_O30kmIE60km_SpecifiedEnsemble.yaml
M	scenarios/ABIAHI120km3denvar.yaml
M	scenarios/IASI120km3denvar.yaml
M	scenarios/IASI30kmIE60km3denvar.yaml
A	scenarios/defaults/enkf.yaml
M	scenarios/defaults/observations.yaml
M	scenarios/eda_OIE60km_WarmStart.yaml
A	scenarios/getkf_OIE60km_WarmStart.yaml
A	scenarios/letkf_OIE60km_WarmStart.yaml
M	test/testinput/3denvar_O30kmIE60km_WarmStart.yaml
A	test/testinput/getkf_OIE120km_WarmStart.yaml
A	test/testinput/letkf_OIE120km_WarmStart.yaml
M	test/testinput/test.yaml

### CODE REVIEW

**Comment by liujake** [comment]
This one should be a separate merge after #202 . Better also provide a list of modified files in the PR message with 'git diff --name-status develop' though we can see them in 'Files Changed'.

**Comment by jjguerrette** [comment]
File list added.  As you suggested, I will not merge until after #202 is merged.  The base branch is set this way in order to show the diffs for this feature.

**Comment by liujake** [comment]
I suggest to create a tag (with a name including date and/or something related to python) before merging the LETKF one. Current version is a major milestone of upgrade.

**Comment by jjguerrette** [comment]
Note to self: add LETKF example that uses a 2d iterator w/o vertical localization

**Review by liujake — APPROVED** [review]
I think this can be merged if it is ready. Non-vertical localization option can be added in another PR or skip (if time is tight).

**Comment by jjguerrette** [comment]
Should be all set for 2d localization in LETKF @liujake.

**Comment by liujake** [comment]
Then feel free to merge.

**Pull request merged**
