### PR TITLE
Add hybrid 30km-60km EnVar scenario with latest 60km covariance

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
- Add `30km-60km3dhybridSpecifiedEnsemble` run

- Update covariance stddev with 0.33 scaling from @byoung-joo

- Adjust variational timings for 60km EnVar related to single-precision build

### Issue closed

None

### Tests completed
Since only modifies timings of full-scale experiments (more iterations than automated test scenario), the one affected test that uses a 60km ensemble B (`3denvar_O30kmIE60km_WarmStart` ) should still pass.  Therefore, testing is not needed.  The new 3dhybrid scenario completed an entire month.  Also confirmed that 80 members in 60km EDA of single-mesh 3denvar finishes the first cycle.  Both used the single-precision bundle build.

### CODE REVIEW

**Review by liujake — APPROVED** [review]

**Review by ibanos90 — APPROVED** [review]
The changes look good to me. I think you can remove the **Issue closed** section from the PR comment or modify it to `Closes: None`

**Comment by jjguerrette** [comment]
> I think you can remove the **Issue closed** section from the PR comment or modify it to `Closes: None`

Thank you @ibanos90 for the reminder!  @liujake, we could create a chain of issues for the year-end experiments we plan to conduct.  Then @ibanos90 and I can at least populate scenario YAMLs for the ones that are already possible.

**Comment by liujake** [comment]
@jjguerrette I just made a test with this branch by ./test.csh. But I just see
```
liuz_3denvar_O30kmIE60km_WarmStart_TEST
liuz_3denvar_OIE120km_WarmStart_TEST
liuz_3dvar_O30kmIE60km_ColdStart_TEST
liuz_3dvar_OIE120km_ColdStart_TEST
liuz_3dvar_OIE120km_WarmStart_TEST
liuz_eda_OIE120km_WarmStart_TEST
```
but not the hybrid scenario output in scratch. Anything else I need to do to turn on hybrid test?

**Comment by jjguerrette** [comment]
Hi @liujake.  You can execute the following from the command-line to start the experiment:
```
./run.csh 30km-60km3dhybridSpecifiedEnsemble
```

Since I already have this experiment completed (currently running extended forecasts), you may wish to modify `finalCyclePoint` in `scenarios/3dhybrid_O30kmIE60km_SpecifiedEnsemble.yaml` or kill the cylc suite after you confirm that it is running correctly.

**Comment by jjguerrette** [comment]
Tests pass.

**Pull request merged**
