### PR TITLE
Update build for 22MAR2023 release

### LINKED ISSUE #209: Create release tag for 22MAR2023 build
Will use latest python-based workflow

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
Update `build/CMakeLists.txt` to prepare for new release tag.

### Issue closed

Closes #209 

### Tests completed
No impact

### CODE REVIEW

**Comment by jjguerrette** [comment]
@liujake, I do not have access to SACA and do not know what the hash should be.

**Review by junmeiban — APPROVED** [review]

**Comment by junmeiban** [comment]
Tested.

**Comment by byoung-joo** [comment]
@jjguerrette , please set [5f62db0](https://github.com/liujake/SACA/commit/5f62db08e77bef94a9a79a708a66e91cfa0d3bef) for SACA.

**Review by liujake — APPROVED** [review]
As saca is not build by default. No need to worry about its hash. Leave it as 'develop' is Ok.

**Comment by liujake** [comment]
Just saw saca hash was provided. Do either way fine with me.

**Pull request merged**
