### PR TITLE
Add hydrometeors in geovars.yaml for all-sky run.

### LINKED ISSUE #179: [Issue Title] allsky DA failure
**Describe the bug**

I got error info when I conduct allsky 3denvar experiments:
```
 --> vars_nlevels: qc not available in MPAS domain or self % templated_fields" 
```

**To Reproduce**
1. [Base scenario]3denvar
2. allsky run

**Expected behavior**
Success run for allsky DA

### PR DESCRIPTION
**Pull request by junmeiban**
### Description
Add hydrometeors in geovars.yaml for all-sky run. No impact for clear-sky experiments.

### Issue closed
Closes #179 

### Tests completed
Not applicable at this time

### CODE REVIEW

**Comment by jjguerrette** [comment]
I guess these are for RTTOV?

**Comment by junmeiban** [comment]
> I guess these are for RTTOV?

No.  These changes are not related RTTOV.
When I ran all-sky DA, I got error: 
```
 --> vars_nlevels: qc not available in MPAS domain or self % templated_fields" 
```
@byoung-joo mentioned the error might be related to some upstream changes (probably OOPS) and suggested to update geovars.yaml. It works for me. That's the reason I made this PR. I will add more info in PR description.

**Comment by jjguerrette** [comment]
If the changes are identical to those already merged to mpas-jedi develop, then we can merge without discussion or tests after the PR message is cleaned up.

**Comment by jjguerrette** [comment]
Otherwise, please submit a PR to mpas-jedi develop also.

**Review by liujake — APPROVED** [review]
This change is needed for some unknown reason. @junmeiban should also make a PR in mpas-jedi repo.

**Review by byoung-joo — APPROVED** [review]

**Comment by byoung-joo** [comment]
This issue seems to be related to saber PR https://github.com/JCSDA-internal/saber/pull/327, which includes a major saber block refactoring.  The given PR includes `geom.variableSizes` in the constructor of `src/saber/oops/ErrorCovariance.h` and `src/saber/oops/Localization.h`. This PR was merged on Oct 12, 2022.

**Comment by jjguerrette** [comment]
All sounds good.  Will merge when source code repo has matching PR.

**Pull request merged**
