### PR TITLE
Update to 16MAR2022 build

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
Use recent build with latest formats of localization and static B files.

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

### CODE REVIEW

**Comment by jjguerrette** [comment]
@metdyn, you'll see in this PR that `amsua_metop-b` has to be commented out in two places in order for the develop branch to pass all tests.

**Comment by ibanos90** [comment]
Hi @jjguerrette, the coefficient files that give the error when reading are related to the B? Is there a way that we can fix that?

**Comment by ibanos90** [comment]
All tests completed successfully.

**Comment by jjguerrette** [comment]
> Hi @jjguerrette, the coefficient files that give the error when reading are related to the B? Is there a way that we can fix that?

The issues is with `amsua_metop-b`. See [here](https://github.com/JCSDA-internal/ufo/issues/1929) for a discussion.  We might not want to merge this PR until that fix is in place.  Then I can uncomment `amsua_metop-b`.

**Comment by ibanos90** [comment]
Thanks @jjguerrette for the information! I agree that it would be better to wait until that is fixed.

**Comment by jamiebresch** [comment]
[amsua_metop-b.SpcCoeff.bin.gz](https://github.com/NCAR/MPAS-Workflow/files/8367718/amsua_metop-b.SpcCoeff.bin.gz)
FYI. I changed the version info in this file from 3 to 2.
The file is gzipped to be accepted by github.

**Comment by jjguerrette** [comment]
> [amsua_metop-b.SpcCoeff.bin.gz](https://github.com/NCAR/MPAS-Workflow/files/8367718/amsua_metop-b.SpcCoeff.bin.gz) FYI. I changed the version info in this file from 3 to 2. The file is gzipped to be accepted by github.

Thank you @jamiebresch!  I will try it this afternoon.

**Comment by jjguerrette** [comment]
Fix from @jamiebresch worked.  Tests passing. Ready for review.

**Comment by ibanos90** [comment]
> Fix from @jamiebresch worked. Tests passing. Ready for review.

Great. I will test it.

**Comment by jjguerrette** [comment]
FYI @ibanos90, maybe still waiting on some info in the UFO issue: https://github.com/JCSDA-internal/ufo/issues/1929

Likely we do not need to wait though.  I still have the old `amsua_metop-b.SpcCoeff.bin` file with internal version 3.  So we can revert any time we need without a PR.

**Comment by ibanos90** [comment]
> FYI @ibanos90, maybe still waiting on some info in the UFO issue: [JCSDA-internal/ufo#1929](https://github.com/JCSDA-internal/ufo/issues/1929)
> 
> Likely we do not need to wait though. I still have the old `amsua_metop-b.SpcCoeff.bin` file with internal version 3. So we can revert any time we need without a PR.

Ok, sounds good. I am approving the PR since I ran the tests and all succeeded.

**Review by ibanos90 — APPROVED** [review]

**Comment by jjguerrette** [comment]
Merging to get up-to-date with latest localization and covariance files.  If we need to use a newer build, somebody can submit a new PR.

**Pull request merged**
