### PR TITLE
BUMP yaml updates

### LINKED ISSUE #174: Update BUMP YAML keys
See https://github.com/JCSDA-internal/mpas-jedi/pull/811

Can do #173 at the same time.

### PR DESCRIPTION
**Pull request by jjguerrette**
### Description
Companion to https://github.com/JCSDA-internal/mpas-jedi/pull/811.  YAML formats are changed for climatological B and localization.  Refactoring only.

Build is updated to 06JAN2023, which will be updated on the merge date to be consistent with develop code on that date.

Some additional changes are made in `ExternalAnalysisToMPAS.csh` to improve its restart behavior when failing on the first attempt.

### Issue closed

Closes #174 

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3dvar_O30kmIE60km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

### CODE REVIEW

**Comment by byoung-joo** [comment]
@jjguerrette ,
B statistics were re-generated with "06JAN2023" build. Can you please update the following lines, too ?
```
    60km:
      bumpCovDir: /glade/p/mmm/parc/bjung/pandac_common/staticB/20230106_prebuilt/60km.NICAS_00
      bumpCovStdDevFile: /glade/p/mmm/parc/bjung/pandac_common/staticB/20230106_prebuilt/60km.CMAT_00/mpas.stddev_0p33.2018-04-15_00.00.00.nc
      bumpCovVBalDir: /glade/p/mmm/parc/bjung/pandac_common/staticB/20230106_prebuilt/60km.VBAL_00
    120km:
      bumpCovDir: /glade/p/mmm/parc/bjung/pandac_common/staticB/20230106_prebuilt/NICAS_00
      bumpCovStdDevFile: /glade/p/mmm/parc/bjung/pandac_common/staticB/20230106_prebuilt/CMAT_00/mpas.stddev_0p33.2018-04-15_00.00.00.nc
      bumpCovVBalDir: /glade/p/mmm/parc/bjung/pandac_common/staticB/20230106_prebuilt/VBAL_00
```

There are some minor changes in the BUMP diagnostics from existing files with "25OCT2022" build. 
A saber bugfix was reported in https://github.com/JCSDA-internal/mpas-jedi/pull/808 .

**Comment by jjguerrette** [comment]
> B statistics were re-generated with "06JAN2023" build. Can you please update the following lines, too ?

Sure @byoung-joo.  Thanks for that.  Do you think I should update the localization files too?  They were last updated with the 10AUG2022 build.

**Comment by byoung-joo** [comment]
In the saber PR message https://github.com/JCSDA-internal/saber/pull/358#issue-1427186980, it is said that "... _The bugfixes will affect the subgrid generation_ ...". 

So I think it might effect the localization files, too if that "subgrid generation" is related to choosing a subgrid for NICAS.

**Comment by jjguerrette** [comment]
Thanks @byoung-joo. I keep getting this error message when trying to generate the localization:
```
!!! ABORT in nam_check on task #000001: ens1_ne/ens1_nsub should be larger than 3
```
See this yaml: `/glade/p/mmm/parc/guerrett/pandac/fixed_input/generate_bumploc/bumploc.yaml`

Unfortunately I do not have a YAML example to follow in mpas-jedi or saber that attempts to generate localization with fixed lengths, but without covariance, correlations, or sample ensembles.

I'm simply executing `run_all.sh` in the same directory as `bumploc.yaml`.

Log file: `/glade/p/mmm/parc/guerrett/pandac/fixed_input120km/bumploc/h=1200.0km_v=6.0km_06JAN2023code_36pe/jedi.log.all`

**Comment by byoung-joo** [comment]
Thanks, @jjguerrette . I will take a look at this.

**Comment by byoung-joo** [comment]
@jjguerrette ,
For my testing, removing `compute covariance`, `compute correlation`, `compute localization`, `compute moments` keys under `bump.drivers` has fixed the issue ! This effectively sets those key as their default values (i.e., false).

**Comment by jjguerrette** [comment]
Thanks BJ.  That seems to be working.  I think I confused this before too that `compute localization` is not for fixed length scales.

**Review by byoung-joo — APPROVED** [review]

**Pull request merged**
