### PR TITLE
Fixed a failure of a test1 case, update verification obs input, and use bending angle

### PR DESCRIPTION
**Pull request by liujake**
### Description
1. The default is set to 36 cores per node for the forecast step, which caused a failure for one 'test1' scenario pointing to Duda's folder missing the MPAS partition file for 288 cores. Set to 32 cores (thus use 256 cores) in the scenario yaml fixed the problem.

2. Update the hofx obs input location for cycling experiments using raw data with bias correction. Those hofx input obs are used for the forecast verification purpose and we'd better use GSI-ncdiag files and bias-corrected radiance data so that the consistent number of obs is used when comparing forecasts from multiple cycling experiments.

3. Use GNSSRO bending angle instead of refractivity

### List of modified files
M       scenarios/3dvar_O30kmIE60km_ColdStart.yaml
M       test/testinput/3dvar_O30kmIE60km_ColdStart.yaml
M       scenarios/defaults/observations.yaml
M       initialize/data/Observations.py

### CODE REVIEW

**Comment by liujake** [comment]
@ibanos90 Bending angle results look good. So I changed the default to use bending angle now. Please review.

**Review by junmeiban — APPROVED** [review]

**Comment by ibanos90** [comment]
> @ibanos90 Bending angle results look good. So I changed the default to use bending angle now. Please review.

Sorry that I missed this. These changes look good!

**Comment by byoung-joo** [comment]
@liujake , I noticed that this PR is also merged to `release/2.0.0` branch. I wonder if current `release/2.0.0` branch of MPAS-Workflow is good for running some experiment. Or are there any further modification planned for `release/2.0.0` ?

**Comment by liujake** [comment]
2.0.0 was cut off from the develop Yesterday. So they are the same now. Good to use 2.0.0 branch.

**Comment by byoung-joo** [comment]
> 2.0.0 was cut off from the develop Yesterday. So they are the same now. Good to use 2.0.0 branch.

Thank you for confirming!

**Pull request merged**
